config/routes.rb
Dicty11::Application.routes.draw do

	root :to => "home#index", :as => :home

	# match '/login' => 'user_sessions#new', :as => :login
	# match '/logout' => 'user_sessions#destroy', :as => :logout

	# match '/admin' => 'user_sessions#admin', :as => :admin

	#DJM match '/register' => 'registration#new', :as => :register 
	#DJM match '/registrations' => 'registration#view', :as => :registrations

	# match '/payment' => 'registration#payment', :as => :payment_redirect
	# match '/users/:id', :to => 'users#show', :as => :user

	# resources :user_sessions
	# resources :users
	# resources :registration

	# resources :abstracts

	# resources :users do
	# 	resources :abstracts
	# end

	# resources :users do
	#   resources :registration
	# end

	match '/agenda' => 'home#agenda', :as => :agenda
	match '/transport' => 'home#transport', :as => :transport
	match '/registration' => 'home#registration', :as => :registration #DJM
	match '/excursion' => 'home#excursion', :as => :excursion #DJM
	match '/abstracts' => 'home#abstracts', :as => :abstracts #DJM
	# match '/sponsors' => 'home#sponsors', :as => :sponsors



end

app/models/abstract.rb
class Abstract < ActiveRecord::Base

	belongs_to :user

	validates_presence_of :title,  :presenter, :abstract, :agreement, :abstract_type, :authors, :address
	validates_inclusion_of :abstract_type, :in => ["Talk", "Poster"], :allow_nil => false

end

app/controllers/abstracts_controller.rb
class AbstractsController < ApplicationController

	skip_before_filter :login_required, :only => [ :index, :show ]
	include UsersHelper

	# GET /abstracts
	# GET /abstracts.xml
	def index
		session[:where_from] = 'abstract'
		if params[:user_id]
			@abstracts = Abstract.find(:all, :conditions =>['user_id = :user_id',
												   {:user_id => params[:user_id] } ])
		else
			@abstracts = Abstract.all
		end

		respond_to do |format|
			format.html # index.html.erb
			format.xml  { render :xml => @abstracts }
			format.csv {

				buffer = FasterCSV.generate do |csv|
					fields = [
						:user_id,
						:title,
						:authors,
						:address,
						:presenter,
						:abstract_type,
						:abstract,
						:agreement,
						:note_to_organizers,
						:created_at,
						:updated_at
					]
					csv << fields.map{|field| field.to_s}
					for abstract in @abstracts
						csv << fields.map{|field| value = abstract.send(field)}
					end
				end
				send_data( buffer, :type => 'text/csv; charset=iso-8859-1; header=present', :filename => 'abstracts.csv')
			}
		end
	end

	# GET /abstracts/1
	# GET /abstracts/1.xml
	def show
		if logged_in?
			@abstract = Abstract.find(params[:id])
			#@abstract = Abstract.where(:user_id => current_user.id).find(params[:id])

			respond_to do |format|
				format.html # show.html.erb
				format.xml  { render :xml => @abstract }
			end
		else
			redirect_to login_path
		end
	end

	# GET /abstracts/new
	# GET /abstracts/new.xml
	def new
		@abstract = Abstract.new( :user_id=>current_user.id )

		respond_to do |format|
			format.html # new.html.erb
			format.xml  { render :xml => @abstract }
		end
	end

	# GET /abstracts/1/edit
	def edit
		@abstract = Abstract.find(params[:id])
	end

	# POST /abstracts
	# POST /abstracts.xml
	def create
		@abstract = Abstract.new(params[:abstract])

		respond_to do |format|
			if @abstract.save
				logger.info "Sending confirmation email for abstract submission to #{User.find(@abstract.user_id)}"

				# Send confirmation emails to user and the host
				RegistrationConfirmation.abstract_confirmation_to_user(@abstract).deliver

				logger.info "Abstract submission successful"

				format.html { redirect_to(@abstract, :notice => 'Abstract was successfully created.') }
				format.xml  { render :xml => @abstract, :status => :created, :location => @abstract }
			else
				format.html { render :action => "new" }
				format.xml  { render :xml => @abstract.errors, :status => :unprocessable_entity }
			end
		end
	end

	# PUT /abstracts/1
	# PUT /abstracts/1.xml
	def update
		@abstract = Abstract.find(params[:id])

		respond_to do |format|
			if @abstract.update_attributes(params[:abstract])
				format.html { redirect_to(@abstract, :notice => 'Abstract was successfully updated.') }
				format.xml  { head :ok }
			else
				format.html { render :action => "edit" }
				format.xml  { render :xml => @abstract.errors, :status => :unprocessable_entity }
			end
		end
	end

	# DELETE /abstracts/1
	# DELETE /abstracts/1.xml
	def destroy
		@abstract = Abstract.find(params[:id])
		@abstract.destroy

		respond_to do |format|
			format.html { redirect_to(abstracts_url) }
			format.xml  { head :ok }
		end
	end
end

app/helpers/abstracts_helper.rb
module AbstractsHelper
end

app/views/abstracts/_form.html.erb
<%= form_for(@abstract) do |f| %>

   <% if @abstract.errors.any? %>
      <div id="error_explanation">
         <h2><%= pluralize(@abstract.errors.count, "error") %> prohibited this abstract from being saved:</h2>
         <ul>
            <% @abstract.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
            <% end %>
         </ul>
       </div>
    <% end %>

   <%= f.hidden_field :user_id %>
   <p>
     <%= f.label :abstract_type %>
     <%= f.radio_button :abstract_type,  "Poster" %>
     <%= f.label :abstract_type, "Poster" %>&nbsp;&nbsp;
     <%= f.radio_button :abstract_type,  "Talk" %>
     <%= f.label :abstract_type, "Talk" %>&nbsp;&nbsp;
   </p>

   <p>
     <%= f.label :title %><br />
     <%= f.text_field :title, :class => "long_field" %>
   </p>
   <p>
     <%= f.label :authors, "List of Authors" %><br />
     <%= f.text_field :authors, :class => "long_field" %>
   </p>
   <p>
     <%= f.label :abstract, "Abstract"%><br />
     <%= f.text_area :abstract, {:rows => 10, :wrap=>"virtual", :class => "long_field" } %>
   </p>
   <p>
     <%= f.label :address, "Address for correspondence" %><br />
     <%= f.text_area :address, {:rows => 2, :wrap=>"virtual", :class => "long_field" } %>    
   </p>

   <p>
     <table>
         <tr>
             <td>
                 <%= f.label :presenter %><br />
                 <%= f.text_field :presenter %>
             </td>
             <td>
                 <%= f.check_box :agreement %>
                 <%= f.label :agreement, "I agree to make my abstract available on the Conference website and at dictyBase" %>
             </td>
         </tr>
     </table>
   </p>
   <p>
     <%= f.label :note_to_organizers %><br />
     <%= f.text_area :note_to_organizers, {:rows => 4, :wrap=>"virtual", :class => "long_field" } %>
   </p>
   
    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/abstracts/edit.html.erb
<h1>Editing abstract</h1>

<%= render 'form' %>
      
<%= link_to 'Show', @abstract %> |
<%= link_to 'Back', abstracts_path %>

app/views/abstracts/index.html.erb
<% content_for :title, "Dicty13: Abstracts" %>

<%= javascript_include_tag "jquery.dataTables.nightly", "jquery", "jquery-dataTables", "TableTools", "ZeroClipboard" %>
<%= stylesheet_link_tag "jquery-dataTables", "jquery-ui-overcast", "TableTools", "TableTools_JUI" %>

<script type="text/javascript">
	$(document).ready(function() {
			$('#abstract').dataTable( {
				//"sScrollX": "500px",
				"bJQueryUI": false,
				"bPaginate": true,
				"sPaginationType": /*"two_button",*/ "full_numbers",
				"bLengthChange": true,
				"bSort": true,
				//"bInfo": false,
				"bAutoWidth": true,

				/*"iDisplayLength": 20,
				  "sDom": 'CT<"clear">lfrtip',
				//"sDom": 'T<"clear"><"H"lTf>rt<"F"ip>',
				"oTableTools": {
				"aButtons": [
				"print",
				{
				"sExtends": "csv",
				"sFileName": "Dicty12_registrations.csv",
				"bFooter": false
				},
				{
				"sExtends": "pdf",
				"sFileName": "Dicty12_registrations.pdf",
				"sTitle": "Dicty12 Registrations",
				"sPdfOrientation": "landscape"
				}
				]

				}*/

			} );
	} );
</script>

<h3>Please submit your abstract no later than July 14, 2013</h3>

<!--<b>The abstract book is available and can be viewed <a href="<%= ENV["RAILS_RELATIVE_URL_ROOT"] %>/Dicty12_Abstract_Book.pdf">here</a></b>.-->

<h4>Abstracts</h4>
<p>To submit your abstracts, please fill out all fields (the 'Note to organizers' field is optional). Abstracts should not exceed 300 words.</p>

<h4>Talks:</h4>
<p>Please plan your talk to be 15 minutes long; your slot will be a maximum of 25 minutes including questions. Please bring your talk on a USB stick or similar, ready to load onto a PC or Mac computer the day of your talk. If you wish to bring your own laptop,  please contact the organisers at the meeting before your scheduled talk.</p>

<h4>Posters:</h4>
</p>The poster size should be 90 cm wide x 110 cm high.</p>

<% if is_admin? %>
	<h4>You are logged in as an ADMIN</h4>
<% end %>
<h3>Submitted abstracts</h3>

<% if @abstracts.empty? %>
	— No abstracts submitted yet —
<% elsif logged_in? %>
	<table class="display" id="abstract">
		<thead>
			<tr>
				<th>Title</th>
				<th>Presenter</th>
				<th>Type</th>
				<th>Submitted</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @abstracts.each do |abstract| %>
				<tr>
					<td>
						<!-- <p class="title"> -->
						<%= link_to abstract.title, abstract_path(abstract.id) %>
						<!-- </p>  -->
						<!-- <p class="presenter"><%#=h abstract.presenter %></p> -->
					</td>
					<td><%=h abstract.presenter %></td>
					<td class="type"><%=h abstract.abstract_type %></td>
					<td>
						<span><%= format_date(abstract.created_at) %></span>
					</td>
					<td>
						<%= link_to 'Show', abstract %> | 
						<%= link_to 'Edit', edit_abstract_path(abstract.id) if can_edit?(abstract) %> | 
						<%= link_to 'Destroy', abstract, :confirm => 'Are you sure?', :method => :delete if is_admin? %></td>
				</td>
			<% end %>
		</tbody>
	</table>
<% else %>
	You have to be logged in to see submitted abstracts
<% end %>

<br/><br/>

<!-- <h3>Abstract submission: </h3> -->

<% if abstract_submission_open? %>
	<% if logged_in? %>
		<p class="button" align="center">
		<%= link_to image_tag("submit-abstract.png", :border=>0), new_abstract_path %>
		</p>
	<% else %>
		<p class="button" align="center">
		<%= link_to image_tag("submit-abstract.png", :border=>0), login_path %>
		</p>
	<% end %>
<% end %>

<!-- <p>Coming soon...</p> -->

app/views/abstracts/new.html.erb
<h1>New abstract</h1>

<%= render 'form' %>

<%= link_to 'Back', abstracts_path %>

app/views/abstracts/show.html.erb
<% if logged_in? %>
   <p id="notice"><%= notice %></p>

   <p>
     <b>Title:</b>
     <%= @abstract.title %>
   </p>

   <p>
     <b>Authors:</b>
     <%= @abstract.authors %>
   </p>

   <p>
     <b>Presenter:</b>
     <%= @abstract.presenter %>
   </p>

   <p>
     <b>Address for correspondence:</b>
     <%= @abstract.address %>
   </p>


   <p>
     <b>Abstract:</b>
     <%= simple_format(@abstract.abstract) %>
   </p>

   <p>
     <b>Abstract type:</b>
     <%= @abstract.abstract_type %>
   </p>


   <% if can_edit?(@abstract) %>
      <%= link_to 'Edit', edit_abstract_path(@abstract) %> |
   <% end %>
   <%= link_to 'Back', abstracts_path %>
<% else %>
   You have to be logged in to see submitted abstracts
<% end %>