config/routes.rb
Dicty11::Application.routes.draw do

	root :to => "home#index", :as => :home

	# match '/login' => 'user_sessions#new', :as => :login
	# match '/logout' => 'user_sessions#destroy', :as => :logout

	# match '/admin' => 'user_sessions#admin', :as => :admin

	#DJM match '/register' => 'registration#new', :as => :register 
	#DJM match '/registrations' => 'registration#view', :as => :registrations

	# match '/payment' => 'registration#payment', :as => :payment_redirect
	# match '/users/:id', :to => 'users#show', :as => :user

	# resources :user_sessions
	# resources :users
	# resources :registration

	# resources :abstracts

	# resources :users do
	# 	resources :abstracts
	# end

	# resources :users do
	#   resources :registration
	# end

	match '/agenda' => 'home#agenda', :as => :agenda
	match '/transport' => 'home#transport', :as => :transport
	match '/registration' => 'home#registration', :as => :registration #DJM
	match '/excursion' => 'home#excursion', :as => :excursion #DJM
	match '/abstracts' => 'home#abstracts', :as => :abstracts #DJM
	# match '/sponsors' => 'home#sponsors', :as => :sponsors



end

app/views/layouts/abstracts.html.erb
<% content_for :content do %>
	<div id="user_nav">
		<% if current_user %>

			<% if is_admin? %>
				<%= link_to "Admin panel", :controller => 'user_sessions', :action => 'admin' %> |
			<% end %>

			<% if has_abstract?(current_user) %>
				<%= link_to 'My abstracts', user_abstracts_path(current_user) %> |
			<% end %>

			<%= link_to "Logout", logout_path %>

		<% else %>

			<%= link_to "Login or sign up", login_path %>

		<% end %>
	</div>

	<%= yield %>

<% end %>

<%= render :file => 'layouts/application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
		<title><%= h(yield(:title) || "Dicty 2015") %></title>
		<%= stylesheet_link_tag 'scaffold' %>
		<%= yield(:head) %>

		<%= stylesheet_link_tag 'ChelseaMarket' %>
		<%= favicon_link_tag '/favicon.ico' %>

		<!-- Google Analytics track code -->
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-16352781-7', 'auto');
		  ga('send', 'pageview');

		</script>
	</head>
	
	<body>
		<div id="container" class="centered"> 
			
			<!-- <div class="onHeaderTop">   </div> -->
			<div class="mainMenu">
				
				<!-- MAIN IMAGE -->
				<%= image_tag("dicty15_header.gif", :height => '300', :width => '850') %>
				
				<!-- MAIN MENU -->
				<div class="menuBelow">

					<span class="menu">
						<%= link_to 'Home', {:controller => 'home',  :action => 'index'}, class: 'hvr-underline-from-center' %>
					</span>

					<span class="menu">
						<%= link_to 'Registration', {:controller => 'home',  :action => 'registration'}, class: 'hvr-underline-from-center' %>
					</span>

					<span class="menu">
						<%= link_to 'Abstracts', {:controller => 'home',  :action => 'abstracts'}, class: 'hvr-underline-from-center' %>
					</span>

					<span class="menu">
						<%= link_to 'Travel', {:controller => 'home',  :action => 'transport'}, class: 'hvr-underline-from-center'  %>
					</span>
					
					<span class="menu">
						<%= link_to 'Agenda', {:controller => 'home',  :action => 'agenda'}, class: 'hvr-underline-from-center'  %>
					</span>

					<span class="menu">
						<%= link_to 'Excursion', {:controller => 'home',  :action => 'excursion'}, class: 'hvr-underline-from-center' %>
					</span>

				</div>

			</div> 
			<!-- END OF HEADER -->

			<div id="content">
				<%= content_for?(:content) ? yield(:content) : yield %>
			</div>

			<div id="footer">
				<p style="text-align:center;">
				Header image credits: Royal Holloway 
				<br/>
				&copy; <a href="http://dictybase.org">dictyBase.org</a> 2015
				</p>
			</div>
		</div>
	</body>
</html>

app/views/layouts/registration.html.erb
<% content_for :content do %>
	<div id="user_nav">

		<% if current_user %>

			<% if is_admin? %>
				<%= link_to "Admin panel", :controller => 'user_sessions', :action => 'admin' %> |
			<% end %>

			<% if is_registered? %>
				<%= link_to 'Registration details', registration_path(current_user)%> |
				<% if DateTime.now <= DateTime.parse('3rd Aug 2013 11:59:00 PM') %>
					<%= link_to 'Edit', edit_registration_path(current_user)%> |
				<% end %>
			<% end %>

			<%= link_to "Logout", logout_path %>

		<% else %>

			<%= link_to "Login or sign up", login_path %>

		<% end %>
	</div>

	<%= yield %>

<% end %>

<%= render :file => 'layouts/application' %>